name: ci
on:
  pull_request:
  push:
    branches:
      - master
  release:
    types: [published]

jobs:
  build-image:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Docker build
        run: make
      - name: Test protoc
        run: make test
      - name: Login to GitHub Container Registry
        if: github.event_name == 'push' || github.event_name == 'release'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy devel
        if: github.event_name == 'push'
        run: |
          docker tag ghcr.io/seqsense/protoc-assets ghcr.io/seqsense/protoc-assets:devel
          docker push ghcr.io/seqsense/protoc-assets:devel
      - name: Deploy release
        if: github.event_name == 'release'
        run: |
          IMAGE_TAG=${GITHUB_REF#refs/tags/}
          docker tag ghcr.io/seqsense/protoc-assets ghcr.io/seqsense/protoc-assets:${IMAGE_TAG}
          docker push ghcr.io/seqsense/protoc-assets:${IMAGE_TAG}
      - name: Write tool versions to release notes
        if: github.event_name == 'release'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          IMAGE_TAG=${GITHUB_REF#refs/tags/}
          echo '## Tool versions' > ./notes
          docker run ghcr.io/seqsense/protoc-assets cat /versions | xargs -L1 echo "-" >> ./notes
          gh release edit ${IMAGE_TAG} \
            --title ${IMAGE_TAG} \
            --notes-file ./notes
