name: ci
on:
  pull_request:
  push:
    branches:
      - master
    tags:
      - '*'

jobs:
  build-image:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker build
        env:
          DOCKER_BUILDKIT: 1
        run: make
      - name: Test protoc
        run: make test
      - name: Login to GitHub Container Registry
        if: github.event_name == 'push'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy devel
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          docker tag ghcr.io/seqsense/protoc-assets ghcr.io/seqsense/protoc-assets:devel
          docker push ghcr.io/seqsense/protoc-assets:devel
      - name: Deploy release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          IMAGE_TAG=${GITHUB_REF#refs/tags/}
          docker tag ghcr.io/seqsense/protoc-assets ghcr.io/seqsense/protoc-assets:${IMAGE_TAG}
          docker push ghcr.io/seqsense/protoc-assets:${IMAGE_TAG}
